[package]
name = "penguin"
version = "0.0.1"
edition = "2021"
authors = ["Braxton Fair"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.0.10", features = ["derive"] }
